language: java

deploy:
  provider: releases
  api_key:
    secure: "1ejdX6YooxpY8iK68Ni33vmMTZzLC46tnOvKHh2Ux5X7cm++sVG98H372scrb8XaHULtn
DJgQMBfkVIkFPdev7xN/KvngIZ8UrQmt97bjSFTOglXnjavrfvJALeh0dIKXvmQGu5TcA9KSYnrLBHFH
Yre+c0Teqtj5/6w9VYnf91xuMGYDNymwQsoNVBwD044BTr3uIftM0ffOz+LuVNC23/ABGX5X89/rAMdX
H0fuFteKfFfqyy9hxH/UfvX98ZW7a7bx7HhgCqn7Llhh9LT1037mDKZjj8feebpD2mIRqY3XxIeleWZB
IPhACeLEXAOBEHAHedO6CHrFjcoIxCwXYwU3P4QYGs3ZOvNE86crq97U3vsrK3wwOE+lL1rUXg8nFf7K
zU30qxSjOUkqoXH5AiYDAY6mpdgPRyOUminocVopnd1r4sd9Mn1BevP9VtuNVE4ovVJBcOHp8YkCMJiI
kCloyKnEkM/k24/vYgzeUCwTvBxCH1gHwLL05tAG1MJ19Oek5rMS4j6/EhhqtOrV5yzrZDTzGpowrHdK
dbnV4X9e/npuLK82mKZxmZQP5HPylzjs/gzKtGcPdmWxJJ5xS7qCDS0TBsAw8q5gp7URM3mbAKDYqO5f
d3C5cqFbC/kaQYNkAGfaseJzD6pKEsX2VB0Nrjf/VP4VyGhRefUcnU="

  file: build/distributions/xld-powercenter-plugin-1.0.7.xldp
  on:
    all_branches: true
    tags: true
    repo: okram999/xld-powercenter-plugin
