language: java

deploy:
  provider: releases
  api_key:
    secure: 9f41b7780570c2d48adc6fa384cfdffa42477564
  file: build/distributions/xld-powercenter-plugin-1.0.7.xldp
  on:
    all_branches: true
    tags: true
    repo: okram999/xld-powercenter-plugin
